name: Build and Release Python Application

permissions:
  contents: write

on:
  push:
     tags: 
       - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # You can choose another OS if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Choose the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Replace with your actual dependency installation command

      - name: Build for Windows
        run: |
          .\pack.bat
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rsa_message_artifacts
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: rsa_message_artifacts

      - name: Update Release Notes
        run: |
          RELEASE_NOTES=$(cat RELEASE.md)

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rsa_message.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
